services:
  app:
    container_name: chat
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../src:/app/src
    environment:
      user: ${user}
      oracle_admin_password: ${oracle_admin_password}
      oracle_db_dsn: ${oracle_db_dsn}
      oracle_cert_path: ${oracle_cert_path}
      auth_config_path: ${auth_config_path}
      gemini_api_key: ${gemini_api_key}
      google_api_key: ${google_api_key}
      google_all_engine_id_cx: ${google_all_engine_id_cx}
      google_reddit_engine_id_cx: ${google_reddit_engine_id_cx}
      reddit_client_id: ${reddit_client_id}
      reddit_client_secret: ${reddit_client_secret}
    networks:
      - chat_network
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    ports:
      - "1080:1080"
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
    cap_add:
      # Docker already have them, these are for podman users
      - MKNOD
      - AUDIT_WRITE
      # additional required cap for warp, both for podman and docker
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp
    networks:
      - chat_network
  # nginx:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile-nginx
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - chat_network

networks:
  chat_network:
    name: chat_network
    driver: bridge
